services:
  nextcloud:
    image: ${NEXTCLOUD_IMAGE}
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PATH: ${NEXTCLOUD_VIRTUAL_PATH}
    networks:
      - reverse-proxy
      - internal

  notify_push:
    image: ${NOTIFY_PUSH_IMAGE}
    environment:
      PORT: "${NOTIFY_PUSH_PORT}"
      NEXTCLOUD_URL: "${NEXTCLOUD_URL}"
      REDIS_URL: "${REDIS_URL}"
      DATABASE_URL: "${DATABASE_URL}"
      DATABASE_PREFIX: "${DATABASE_PREFIX}"
      LOG: "${NOTIFY_PUSH_LOG}"
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PATH: ${NOTIFY_PUSH_VIRTUAL_PATH}
      VIRTUAL_DEST: ${NOTIFY_PUSH_VIRTUAL_DEST}
      VIRTUAL_PORT: "${NOTIFY_PUSH_PORT}"
    expose:
      - "${NOTIFY_PUSH_PORT}"
    networks:
      - reverse-proxy
      - internal
      - redis
      - postgres

networks:
  internal:
    driver: bridge
  reverse-proxy:
    external: true
  redis:
    external: true
  postgres:
    external: true
